a_core/urls.py
from django.contrib import admin
from django.urls import path
from a_posts.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('category/<tag>/',home_view, name='category'),
    path('',home_view, name='home'),
    path('post/create/',post_create_view, name='post-create'),
    path('post/delete/<pk>/',post_delete_view, name='post-delete'),
    path('post/edit/<pk>/',post_edit_view, name='post-edit'),
    path('post/<pk>/',post_page_view, name='post'),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

a_posts/models.py
from django.db import models
import uuid
# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=400)
    artist = models.CharField(max_length=500, null=True)
    url = models.URLField(max_length=500, null=True)
    image = models.URLField(max_length=500)
    body = models.TextField()
    tags = models.ManyToManyField('Tag')
    created = models.DateTimeField(auto_now_add=True)
    id = models.CharField(max_length=100, default=uuid.uuid4, primary_key=True, editable=False)
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-created']
    
    
class Tag(models.Model):
    name = models.CharField(max_length=20)
    image = models.FileField(upload_to='icons/', null=True, blank=True)
    slug = models.SlugField(max_length=20, unique=True)
    order = models.IntegerField(null=True)
    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['order']

a_posts/forms.py
from django.forms import ModelForm
from django import forms
from .models import *


class PostCreateForm(ModelForm):
    class Meta:
        model = Post
        fields = ['url', 'body', 'tags']
        labels = {
            'body' : 'Caption',
            'tags' : 'Category',
        }
        widgets = {
            'body' : forms.Textarea(attrs={'rows':3, 'placeholder':'Add a caption ...', 'class':'font1 text-4xl'}),
            'url' : forms.TextInput(attrs={'placeholder':'Add url ...'}),
            'tags' : forms.CheckboxSelectMultiple(),
        }
        
        
class PostEditForm(ModelForm):
    class Meta:
        model = Post
        fields = ['body', 'tags']
        labels = {
            'body' : '',
            'tags' : 'Category'
        }
        widgets = {
            'body' : forms.TextInput(attrs={'rows':3, 'class':'font1 text-4xl'}),
            'tags' : forms.CheckboxSelectMultiple(),
        }

a_posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
from bs4 import BeautifulSoup
import requests
from django.contrib import messages

def home_view(request, tag=None):
    if tag:
        posts = Post.objects.filter(tags__slug = tag)
        tag = get_object_or_404(Tag, slug=tag)
    else:
        posts = Post.objects.all()
        
    categories = Tag.objects.all()

    context = {
        'posts':posts,
        'categories': categories,
        'tag' : tag
    }
    
    return render(request, 'a_posts/home.html', context )



def post_create_view(request):
    form = PostCreateForm()

    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            
            website = requests.get(form.data['url'])
            sourcecode = BeautifulSoup (website.text, 'html.parser')
            find_image = sourcecode.select('meta[content^="https://live.staticflickr.com/"]') 
            print(find_image)
            image = find_image[0]['content']
            post.image = image
            
            find_title = sourcecode.select('h1.photo-title')
            title = find_title[0].text.strip()
            post.title = title
            
            find_artist = sourcecode.select('a.owner-name')
            artist = find_artist[0].text.strip()
            post.artist = artist
            
            post.save()
            form.save_m2m()
            return redirect('home')

    return render(request, 'a_posts/post_create.html', {'form': form})


def post_delete_view(request, pk):
    post = get_object_or_404(Post, id=pk)
    if request.method == 'POST':
        post.delete()
        messages.success(request, 'Post Deleted')
        return redirect('home')
    return render(request, 'a_posts/post_delete.html',{'post':post})


def post_edit_view(request, pk):
    post = get_object_or_404(Post, id=pk)
    form = PostEditForm(instance=post)
    if request.method == 'POST':
        form = PostEditForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'Post Updated')
            return redirect('home')
    context = {
        'post':post,
        'form':form
    }
    return render(request, 'a_posts/post_edit.html',context)


def post_page_view(request, pk):
    post = get_object_or_404(Post, id=pk)
    return render(request, 'a_posts/post_page.html',{'post':post})

templates/a_posts/home.html
{% extends "layouts/a.html" %}

{% block content %}

{% for post in posts %}

{% include "a_posts/post.html" %}
    
{% endfor %}

{% endblock %}

templates/a_posts/post.html
<article class="card">
    <div class="flex items-center justify-between px-4 h-14">
        <h3 class="text-start leading-5 mr-1">{{ post.title }}</h3>
        <div class="text-sm text-gray-400 truncate">flickr<a href="{{ post.url }}" class="hover:underline ml-1" target="blank">{{ post.artist }}</a></div>
    </div>
    <figure>
        <a href="{% url 'post' post.id %}"><img class="w-full" src="{{ post.image }}"></a>
    </figure>
    <div class="p-4 pb-2">
        <a class="flex items-center gap-1 mb-4" href="">
            <img class="w-8 h-8 object-cover rounded-full" src="https://img.icons8.com/small/96/A9A9A9/happy.png">
            <span class="font-bold hover:underline">Lisa</span>
            <span class="text-sm text-gray-400">@lisasimpson</span>
        </a>
        <p class="text-5xl mb-10 px-4 font1">{{ post.body }}</p>
        <div class="flex items-center gap-2 text-sm mb-5 flex-wrap">
            {% for tag in post.tags.all %}
            <a href="{% url 'category' tag.slug %}" class="bg-gray-200 rounded-full px-3 py-1 hover:bg-gray-800 hover:text-white">{{ tag }}</a>
            {% endfor %}
        </div>
        <div class="flex items-center justify-between text-sm px-2">
            <a class="font-bold hover:underline" href="{% url 'post' post.id %}">
                Comments
                <span class="font-light text-gray-500 ml-1">3</span>
            </a>
            <div class="flex items-center gap-4 [&>a:hover]:underline">
                <div class="flex items-center gap-1">
                    <img class="w-5 -mt-1" src="https://img.icons8.com/small/24/000000/fire-heart.png">
                    1
                </div>
                <a href="">Like</a>
                <a href="{% url 'post-edit' post.id %}">Edit</a>
                <a href="{% url 'post-delete' post.id %}">Delete</a>
            </div>
        </div>
    </div>
</article>

templates/a_posts/post_create.html
{% extends "layouts/b.html" %}

{% block content %}

<h1>Create Post</h1>
<div class="card !p-8">
    
    <div class="flex items-center mb-6">
        <img class="h-5 object-cover mr-1" src="https://img.icons8.com/small/96/333333/search--v1.png"/>
        <a href="https://www.flickr.com/explore" target="_blank" class="hover:underline text-gray-500">Find an image on Flickr</a>
    </div>

    <form method='POST'>
        {{ form.as_p }}
        {% csrf_token %}
        <button type="submit" class="mt-1">Submit Post</button>
        <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
    </form>
</div>

{% endblock content %}

templates/a_posts/post_delete.html
{% extends "layouts/b.html" %}

{% block content %}

<div class="md:flex items-center">
    <div class="w-full md:max-w-sm mr-6 md:[&>*>*>p]:text-4xl">

        {% include "a_posts/post.html" %}

    </div>
    <div>
        <h1>Delete Post</h1>
        <p class="mb-6">Are you sure you want to delete this post?</p>
        
        <form method='POST'>
            {% csrf_token %}
            <button type="submit">Confirm</button>
            <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Go Back</a>
        </form>
    </div>
</div>

{% endblock content %}

templates/a_posts/post_edit.html
{% extends "layouts/b.html" %}

{% block content %}
<h1>Edit Post</h1>
<div class="card p-4">
    <div class="flex items-center mb-4">
        <img class="w-20 h-20 object-cover rounded-xl mr-4" src="{{ post.image }}">
        <h3 class="text-lg font-bold">{{ post.title }}</h3>
    </div>
    
    <div class="pb-2">
        <form method='POST'>
            {% csrf_token %}
            {{ form }}
            <div class="pt-4">
                <button type="submit">Submit</button>
                <a class="button secondaryAction ml-1" href="">Go Back</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/a_posts/post_page.html
{% extends "layouts/b.html" %}

{% block content %}

{% include "a_posts/post.html" %}

<div class="card !pb-0 -mt-3">
    <form method="POST" class="flex items-center p-4" autocomplete="off">
        <input type="text" name="comment" placeholder="Add comment ..." maxlength="150">
        <button @click="open = false" class="block ml-2" type="submit">Submit</button>
    </form>
</div>

<div class="mb-20">
    <div id="tabs" class="ml-4 flex gap-1 mb-4">
        <a class="tab selected">Newest First</a> 
        <a class="tab">Top Comments</a>
    </div>

    <div id="tab-contents">

        <comment class="card p-4 !mb-4">
            <div class="flex justify-between items-center"> 
                <a class="flex items-center gap-1 mb-2" href="">
                    <img class="w-8 h-8 object-cover rounded-full" src="https://img.icons8.com/small/96/A9A9A9/happy.png"> 
                    <span class="font-bold hover:underline">Bart</span>
                    <span class="text-sm font-normal text-gray-400">@bartsimpson</span>
                </a>
            </div>
            <p class="text-xl px-2">
                This is a comment from Bart
            </p>
            <div x-data="{ repliesOpen: false }" class="flex items-center justify-between flex-wrap text-sm px-2">
                <a @click="repliesOpen = !repliesOpen" class="font-bold hover:underline cursor-pointer">
                    <div class="inline-block" x-bind:class="repliesOpen && 'rotate-90 duration-300'">
                        <svg transform ="rotate(90)" width="9" height="9" viewBox="0 0 25 25">
                            <path d="M24 22h-24l12-20z"/>
                        </svg>
                    </div>
                    Replies
                    <span class="font-light text-gray-500 ml-1">1</span>
                </a>
                <div class="flex items-center gap-4 [&>a:hover]:underline">
                    <div class="flex items-center gap-1">
                        <img class="w-5 -mt-1" src="https://img.icons8.com/small/24/000000/fire-heart.png">
                        1
                    </div>
                    <a href="">Like</a>
                    <a href="">Delete</a>
                </div>

                <div x-show="repliesOpen" x-cloak class="basis-full mt-3 pl-8 grid grid-cols-1">

                    <reply class="flex items-end justify-between py-4 border-t">
                        <div class="flex">
                            <a href="">
                                <img class="w-8 h-8 object-cover rounded-full mr-2" src="https://img.icons8.com/small/96/A9A9A9/happy.png">
                            </a>
                            <div class="w-fit">
                                <a class="block" href="">
                                    <span class="font-bold hover:underline">Homer</span>
                                    <span class="text-sm text-gray-400">@homersimpson</span>
                                </a>
                                <div class="mr-3">This is a reply from Homer</div>
                            </div>
                        </div>
                        <div class="flex items-center gap-4 [&>a:hover]:underline">
                            <div class="flex items-center gap-1">
                                <img class="w-5 -mt-1" src="https://img.icons8.com/small/24/000000/fire-heart.png">
                                1
                            </div>
                            <a href="">Like</a>
                            <a href="">Delete</a>
                        </div>
                    </reply>

                    <form method="POST" class="replyform flex justify-between" autocomplete="off">
                        <input type="text" name="reply" placeholder="Add reply ..." maxlength="150">
                        <button class="block" type="submit">Submit</button>
                    </form>
                </div>
            </div> 
        </comment>

    </div>
</div>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Awesome</title>
    <link rel="shortcut icon" type="image/png" href="https://img.icons8.com/small/64/000000/fire-heart.png"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
    <script src="https://cdn.tailwindcss.com"></script>
    <style type="text/tailwindcss">
        [x-cloak] { 
            display: none !important; 
        }
        :root {
            --primary: rgb(88, 40, 244);
            --primary-hover: rgb(69, 29, 200);
            --black: #1f2937;
            --font1: 'Lobster', sans-serif;
        }
        h1 {
            @apply text-4xl font-bold mb-4
        }
        h2 {
            @apply text-2xl font-bold mb-3
        }
        h3 {
            @apply text-lg font-bold 
        }
        .font1 {
            font-family: var(--font1);
        }
        .button, button, [type='submit'], [type='button'] {
            display: inline-flex;
            flex-wrap: wrap;
            align-items: center;
            justify-content: center;
            flex-shrink: 0;
            text-align: center;
            border-radius: 0.5rem;
            cursor: pointer;
            padding: 0 1rem;
            min-height: 3.3rem;
            font-weight: 600;
            box-shadow: 0 4px 3px rgba(0, 0, 0, 0.1);
            transition-property: transform;
            transition-duration: .2s;
            color: white;
            background-color: var(--primary);
            width: fit-content;
        }
        .button:hover, button:hover, [type='submit']:hover, [type='button']:hover {
            background-color: var(--primary-hover);
        }
        .button:active, button:active, [type='submit']:active, [type='button']:active {
            transform: scale(0.95);
        }
        .secondaryAction {
            background-color: white;
            color: rgba(0, 0, 0, 0.6);
            border: 1px solid rgba(0, 0, 0, 0.3);
        }
        .secondaryAction:hover, .button.secondaryAction:hover {
            background-color: rgba(0, 0, 0, 0.05);
        }
        .navitems>li>a {
            @apply flex items-center gap-2 h-12 px-4 hover:bg-gray-700 rounded-lg;
        }
        .card {
            display: flex;
            flex-direction: column;
            overflow: hidden;
            position: relative;
            border-radius: 1rem;
            box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1);
            margin-bottom: 2rem;
            background-color: white;
            padding-bottom: 1rem;
            width: 100%;
        }
        .hoverlist>* {
            @apply hover:bg-gray-100 rounded-md transition duration-150;
        }
        .hoverlist>*>a {
            @apply flex items-center p-2;
        }
        .highlight {
            @apply !bg-indigo-100;
        }
        .titleBlip {
            animation: 1s fadeIn;
        }
        @keyframes fadeIn {
            0% { opacity: 0; }
            10% { opacity: 0; }
            100% { opacity: 1; }
        }
        html, body {
            margin: 0;
            min-height: 100%;
        }
        p {
            margin-bottom: 1rem;
        }
        form p {
            display: flex;
            align-items: center;
            margin-bottom: 1rem;
        }
        label, input {
          display: inline-block;
        }
        form p label {
            width: 7rem;
            }
        label {
            margin: 6px 0 3px;
        }
        input, textarea {
            width: 100%;
        }
        input[type="file"], select {
            background-color: white;
            padding-left: 0;
        }
        label[for="id_remember"] {
            width: auto;
            margin-right: 0.5rem;
        }
        input[name="remember"] {
            width: auto;
        }
        .btn-red {
            @apply inline-flex bg-red-500;
        }
        .btn-red:hover {
            @apply bg-red-600;
        }
        .login .secondaryAction {
            box-shadow: none;
            display: block;
            padding: none;
            padding: 0px;
            border: none;
            font-size: smaller;
            font-weight: normal;
            min-height: auto;
            margin-bottom: 1.5rem;
        }
        .login .secondaryAction:hover {
            @apply text-gray-500 underline bg-white;
        }
        #id_tags {
            margin-bottom: 1rem;
        }
        #id_tags div {
            display: inline-block;
            margin-right: 0.5rem;  
        }
        #id_tags div label {
            border-radius: 9999px;
            padding: 0.5rem 1rem;
            border: 1px solid rgb(229 231 235);
            width: auto;
            cursor: pointer;
            user-select: none;
        }
        #id_tags input {
            display: none;
        }
        #id_tags label:has(input:checked) {
            background-color: var(--black);
            color: white;
            border: 1px solid var(--black);
        }
        .textarea, textarea {
            margin-bottom: 1rem;
        }
        .textarea, textarea, input {
            border-radius: 0.5rem;
            padding: 1rem 1.2rem;
            background-color: rgba(232, 240, 254, 1);
        }
        .errorlist li {
            color: rgb(253, 88, 49);
            padding: 0.5rem;
            padding-left: 1rem;
            border-left: 5px solid rgb(253, 88, 49);
            margin-bottom: 1rem;
        }
        .tab {
            cursor: pointer;
            padding: 0.75rem 1rem;
            color: rgb(0,0,0,0.6); 
            background-color: rgb(0,0,0,0.05);
            border-radius: 0.75rem;
            text-align: center;
            display: flex;
            align-items: center;
        }
        .tab:hover {
            background-color: rgb(0,0,0,0.1);
        }
        .tab.selected {
            color: white;
            background-color: var(--black);
        }
        .replyform {
            border-top: none;
        }
        .replyform textarea, .replyform input {
            padding: 0.75rem 1rem;
            font-size: 1rem;
            margin-bottom: 0px;
            height: 3.2rem;
        }
        .replyform button {
            margin-left: 0.5rem;
            min-height: unset;
        }
        .fade-me-in.htmx-settling{
            opacity: 0;
        }
        .fade-me-in {
            opacity: 1;
            transition: opacity 1s ease-out;
        }
        #profile article figure img {
            @apply aspect-[3/2] object-cover;
        }
        #profile article p {
            @apply truncate leading-normal;
        }
    </style>
</head>
<body class="bg-gray-100">

{% include "includes/messages.html" %}
{% include "includes/header.html" %}


{% block layout %}
  
{% endblock layout %}

    
</body>
</html>

templates/includes/header.html
{% load static %}
<header x-data="{ mobilenavOpen: false }" class="md:flex items-center justify-between [&>*]:px-8 bg-gray-800 h-20 text-white sticky top-0 z-40">
    <div class="flex items-center justify-between h-20">
        <logo>
            <a class="flex items-center gap-1" href="/">
                <img class="w-7 mr-1 -mt-1" src="{% static 'images/fireheart_white.svg' %}"/>
                <span class="text-lg font-bold">Awesome</span>
            </a>
        </logo>
        <mobileicon class="md:hidden">
            <a @click="mobilenavOpen = !mobilenavOpen" class="h-12 w-12 flex items-center justify-center cursor-pointer hover:bg-gray-700 rounded-lg">
                <img x-show="!mobilenavOpen" class="w-6 h-6 select-none" src="https://img.icons8.com/small/64/ffffff/menu.png"/> 
                <img x-show="mobilenavOpen" x-cloak class="w-6 h-6 select-none" src="https://img.icons8.com/small/64/ffffff/delete-sign.png"/>
            </a>
        </mobileicon>
    </div>
    <nav x-show="mobilenavOpen" x-cloak class="md:!block bg-gray-800 h-screen w-screen md:h-auto md:w-auto -mt-20 md:mt-0 absolute md:relative z-[-1]"
    x-transition:enter="duration-300 ease-out"
    x-transition:enter-start="opacity-0 -translate-y-96"
    x-transition:enter-end="opacity-100 translate-y-0">
        <ul class="flex items-center navitems flex-col md:flex-row gap-8 md:gap-0 justify-center h-full -translate-y-10 md:translate-y-0">
            <li><a href="/">Home</a></li>
            <li><a href="{% url 'post-create' %}">Create Post</a></li>
            <li x-data="{ dropdownOpen: false }" class="relative">
                <a @click="dropdownOpen = !dropdownOpen" @click.away="dropdownOpen = false" class="cursor-pointer select-none">
                    <img class="h-8 w-8 rounded-full object-cover" src="https://pbs.twimg.com/profile_images/508601156767997952/fFTdKUf2_400x400.jpeg"/>
                    Bart
                    <img x-bind:class="dropdownOpen && 'rotate-180 duration-300'" class="w-4" src="https://img.icons8.com/small/32/777777/expand-arrow.png"/>
                </a>
                <div x-show="dropdownOpen" x-cloak class="absolute right-0 bg-white text-black shadow rounded-lg w-40 p-2 z-20"
                x-transition:enter="duration-300 ease-out"
                x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
                x-transition:enter-end="opacity-100 translate-y-0 scale-100">
                    <ul class="hoverlist [&>li>a]:justify-end">
                        <li><a href="">My Profile</a></li>
                        <li><a href="">Edit Profile</a></li>
                        <li><a href="">Log Out</a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </nav>
</header>

templates/includes/hero.html
<hero class="grid bg-gray-700 text-white text-center bg-cover z-10 relative bg-[url('https://live.staticflickr.com/65535/49909538937_3255dcf9e7_b.jpg')]">
    <div class="col-start-1 row-start-1 bg-gray-800 bg-opacity-40 w-full h-full"></div>
    <div class="col-start-1 row-start-1 py-24 px-10 ">
        <h1 class="font1 text-6xl title-fadein">Awesome Photos & Captions</h1>
        <p class="text-lg font-bold mb-5">Share your favorite Photos from Flickr and add a great caption</p>
        <a class="button" href="">Get Started</a>
    </div>
</hero>

templates/includes/messages.html
{% if messages %}
<div x-data="{ showMessage: false }" >
{% for message in messages %}
<div x-cloak class="absolute mx-auto left-0 right-0 mt-2 max-w-xl z-50 flex items-center 
            {% if message.tags == 'error' %}bg-red-500{% else %}bg-amber-300{% endif %} text-white p-3 rounded-lg" role="alert"
    x-show="showMessage" 
    x-init="setTimeout(() => showMessage = true, 200), setTimeout(() => showMessage = false, 6000)"
    x-transition:enter="duration-700 ease-out"
    x-transition:enter-start="opacity-0 -translate-y-5"
    x-transition:enter-end="opacity-100 translate-y-0"
    x-transition:leave="duration-200 ease-in"
    x-transition:leave-start="opacity-100 translate-y-0"
    x-transition:leave-end="opacity-0 -translate-y-5">
        <svg class="w-8 h-8 mr-2"  viewBox="0 0 512 512">
            <path d="M315.27,33,96,304H224L192.49,477.23a2.36,2.36,0,0,0,2.33,2.77h0a2.36,2.36,0,0,0,1.89-.95L416,208H288L319.66,34.75A2.45,2.45,0,0,0,317.22,32h0A2.42,2.42,0,0,0,315.27,33Z" style="fill:none;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px" fill="white"></path>
        </svg>
        <div>
            <div class="text-lg">{{ message }}</div>
        </div>
        <div class="ml-auto cursor-pointer" @click="showMessage = false">
            <svg fill="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" viewBox="0 0 24 24" stroke="currentColor" class="w-8 h-8 ml-2">
                <path d="M6 18L18 6M6 6l12 12"></path>
            </svg>
        </div>
    </div> 
{% endfor %}
</div>
{% endif %}

templates/includes/sidebar.html
{% load static %}
<aside x-show="mobileSidebarOpen" x-cloak class="md:!block col-span-full md:col-span-1 lg:mr-[20%] order-1 md:order-2"
x-transition:enter="duration-300 ease-out"
x-transition:enter-start="opacity-0 -mt-96"
x-transition:enter-end="opacity-100 mt-0">
    <section class="card p-4">
        <h2>Categories</h2>
        <ul class="hoverlist">
            {% for category in categories %}
            <li class=" {% if category.slug == tag.slug %}highlight{% endif %}">
                <a href="{% url 'category' category.slug %}">
                    <img class="w-8 h-8 object-cover mr-2" src="{{ category.image.url }}">
                    <span class="font-bold text-sm">{{ category.name }}</span>
                </a>
            </li>
            {% endfor %}
        </ul>
    </section>
    <section class="card p-4">
        <div class="flex items-center">
            <img class="w-7 mr-2 -mt-3" src="{% static 'images/fireheart_black.svg' %}"/>
            <h2>Top Posts</h2>
        </div>
        <ul class="hoverlist">
            <li>
                <a href="" class="flex items-stretch justify-between">
                    <div class="flex items-center truncate">
                        <img class="w-10 h-10 rounded-lg object-cover mr-3 shrink-0" src="https://live.staticflickr.com/65535/50618365686_36f887ab88_c.jpg">
                        <img class="w-6 h-6 rounded-full object-cover mr-1" src="https://img.icons8.com/small/96/A9A9A9/happy.png">
                        <span class="font-bold text-sm mr-1">Homer</span>
                    </div>
                    <span class="text-sm font-light text-grey-500 shrink-0">3 Likes / 1</span>
                </a>
            </li>
            <li>
                <a href="" class="flex items-stretch justify-between">
                    <div class="flex items-center truncate">
                        <img class="w-10 h-10 rounded-lg object-cover mr-3" src="https://live.staticflickr.com/65535/50618365686_36f887ab88_c.jpg">
                        <img class="w-6 h-6 rounded-full object-cover mr-1" src="https://img.icons8.com/small/96/A9A9A9/happy.png">
                        <span class="font-bold text-sm mr-1">Homer</span>
                    </div>
                    <span class="text-sm font-light text-grey-500 shrink-0">3 Likes / 1</span>
                </a>
            </li>
        </ul>
    </section>
    <section class="card p-4">
        <div class="flex items-center">
            <img class="w-7 mr-2 -mt-3" src="{% static 'images/fireheart_black.svg' %}"/>
            <h2>Top Comments</h2>
        </div>
        <ul class="hoverlist">
            <li>
                <a href="" class="flex items-stretch justify-between">
                    <div class="flex items-center truncate">
                        <img class="w-6 h-6 rounded-full object-cover mr-1" src="https://img.icons8.com/small/96/A9A9A9/happy.png">
                        <span class="font-bold text-sm mr-1 truncate">Homer : Comment</span>
                    </div>
                    <span class="text-sm font-light text-grey-500 shrink-0">3 Likes / 1</span>
                </a>
            </li>
            <li>
                <a href="" class="flex items-stretch justify-between">
                    <div class="flex items-center truncate">
                        <img class="w-6 h-6 rounded-full object-cover mr-1" src="https://img.icons8.com/small/96/A9A9A9/happy.png">
                        <span class="font-bold text-sm mr-1 truncate">Homer : Comment</span>
                    </div>
                    <span class="text-sm font-light text-grey-500 shrink-0">3 Likes / 1</span>
                </a>
            </li>
        </ul>
    </section>
</aside>

templates/layouts/a.html
{% extends "base.html" %}

{% block layout %}

{% include "includes/hero.html" %}

<content x-data="{ mobileSidebarOpen: false }" class="grid grid-cols-3 max-w-7xl mx-auto my-6 px-6">
    <mobileSidebarNav class="md:hidden col-span-full mx-auto mb-6 z-10 relative">
        <a @click="mobileSidebarOpen = !mobileSidebarOpen" class="flex items-center cursor-pointer select-none font-bold hover:bg-gray-200 rounded-lg p-3">
            <span>Categories</span>
            <img x-bind:class="mobileSidebarOpen && 'rotate-180 duration-300'" class="w-4 ml-1.5" src="https://img.icons8.com/small/32/000000/expand-arrow.png" />
        </a>
    </mobileSidebarNav>
    <main class="col-span-full md:col-span-2 md:mr-[5%] lg:mx-[10%] order-2 md:order-1">

        {% block content %}
        
        {% endblock content %}

    </main>
    {% include "includes/sidebar.html" %}
 </content>
{% endblock layout %}

templates/layouts/b.html
{% extends "base.html" %}

{% block layout %}

    <content class="block max-w-3xl mx-auto my-12 px-6">
        {% block content %}
        
        {% endblock content %}

    </content>
{% endblock layout %}